image: node:8.12
pipelines:
  default:
    - step:
        script:
          # install dependencies
          - apt-get update
          - apt-get --yes install zip
          - npm install -g grunt-cli
          - npm install -g json
          - npm install

          # build the project
          - npm run build

          # get the current version of the project
          - VERSION=$(json -f ./package.json version)

          # zip the output
          - pushd "./release/snake $VERSION"
          - zip -r "../../snake $VERSION.zip" *
          - popd

          # upload to the 'downloads' section of the bitbucket project
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/drk4/snake/downloads" --form files=@"snake $VERSION.zip"
